# 项目名称、版本、版权年份
#after90s:
#  name: after90s
#  version: 1.1.4
#  copyrightYear: 2018
#  profile: D:/profile/
#开发环境配置
server:
  #端口
  port: 8099
#日志配置
logging:
  level:
#  打印当前里程序用Logger输出的DEBUG信   只打印指定包的日志输出级别com.after90s
    com.after90s: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug 
 #Spring配置
spring:
  redis:
      # Connection URL
      url: redis://localhost:6379
#      pool:
#            maxActive: 8  # 连接池最大连接数（使用负值表示没有限制）
#            maxWait: 800 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#            maxIdle: 8 # 连接池中的最大空闲连接
#            minIdle: 2 # 连接池中的最小空闲连接
      timeout: 2000 # 连接或读取超时时长（毫秒）
  messages:
    #国际化资源文件路径
    basename: i18n/messages
    encoding: UTF-8
#  cache:
#        type: ehcache
#        ehcache:
#          config: ehcache-shiro.xml
  output: 
    ansi: 
      enabled: ALWAYS
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  datasource: 
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/after90s?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver 
    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    自定义用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5    
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.after90s.core.*
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
# Shiro相关
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEbabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
  